version: "3.3"
services:
  database:
    image: "postgres"
    restart: "always"
    container_name: postgres
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes: 
      - ${DOCKER_LOCAL_VOLUME}:${DOCKER_DB_VOLUME}
    networks:
      - "postgres"
    ports:
      - 5432:5432

networks:
  postgres:
    driver: "bridge"