version: "3.3"
services:
  database:
    image: "postgres:16"
    restart: "always"
    container_name: postgres
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes: 
      - ${DOCKER_LOCAL_VOLUME}:${DOCKER_DB_VOLUME}
    networks:
      - "postgres"
    ports:
      - 5432:5432
  im-worker:
    build: ./client/imClient
    container_name: im-worker
    restart: always
    volumes: 
    - ${DOCKER_LOCAL_MOUNT}/im-worker-cache:/home/im-worker

networks:
  postgres:
    driver: "bridge"