# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build&Deploy

on:
  push:
    branches: [ "main" ]

env:
  GOOS: linux
  GOARCH: arm64
  CGO_ENABLED: 1
  CC: aarch64-linux-gnu-gcc
  CXX: aarch64-linux-gnu-g++

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: true    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -o=./imbot -v .

    - name: Test
      run: go test -v ./...

    - name: Deploy
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        goose -dir=schemas sqlite3 ${{secrets.RUNTIME_DIRECTORY}}/${{secrets.DB_NAME}} up
        sudo systemctl stop imbot
        mv imbot ${{secrets.RUNTIME_DIRECTORY}}/imbot
        sudo systemctl start imbot
        
