# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build&Deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main", "feature/postgres-db" ]

env:
  GOOS: linux
  GOARCH: arm64
  CGO_ENABLED: 1
  CC: aarch64-linux-gnu-gcc
  CXX: aarch64-linux-gnu-g++

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: true    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -o=./imbot -v .

    - name: Test
      run: go test -v ./...
  
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Deploy Containers
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        echo "DB_USER="${{secrets.DB_USER}} > .env && \
        echo "DB_PASS="${{secrets.DB_PASS}} >> .env && \
        echo "DB_NAME="${{secrets.DB_NAME}} >> .env && \
        echo "DOCKER_DB_VOLUME="${{secrets.DOCKER_DB_VOLUME}} >> .env && \
        echo "DOCKER_LOCAL_VOLUME="${{secrets.DOCKER_LOCAL_VOLUME}} >> .env && \
        sudo docker compose up -d

    - name: Deploy Imbot
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        goose -dir=schemas postgres "user=${{secrets.DB_USER}} password=${{secrets.DB_PASS}} dbname=${{secrets.DB_NAME}} ${{secrets.DB_EXTRA}}" up
#        sudo systemctl stop imbot
#        mv imbot ${{secrets.RUNTIME_DIRECTORY}}/imbot
#        sudo systemctl start imbot